model:
  class_path: encoders.experiment.VideoTextExp
  init_args:
    initial_lr: 0.0001
    weight_decay: 0.001
    num_warmup_steps: 500
    optimizer: Adam8bit
    hard_negatives: true
    #tokenizer: Qwen2VLProcessor (I don't quite understand here, don't the text encoder and video encoder have their own tokenizers? Why do we need to initialize one for the whole class?)
    #processor: Qwen2VLProcessor (same question as the tokenizer)
    #zeroshot: false (we don't need this since we don't have a zeroshot eval function?)

    text_encoder_cfg:
      name: path/to/jinaai/jina-embeddings-v3
      task: retrieval.query
      truncate_dim: 1024  # The matryoshka dimension
      proj_size: 512

        
        
