data_cfg:
  "stage": "fit"
  "batch_size": 3
  "max_length": 128
  "num_workers": 0 
model:
  class_path: encoders.experiment.VideoTextExp
  init_args:
    optimizer: Adam8bit
    optimizer_cfg: 
      initial_lr: 0.0001
      weight_decay: 0.001
      num_warmup_steps: 500
  
    text_encoder_cfg:
      model_name: jinaai/jina-embeddings-v3
      task: text-matching
      out_hidden_size: 1024  # The matryoshka dimension

    video_encoder_cfg:
      model_name: Qwen/Qwen2.5-VL-3B-Instruct
      depth: 32
      fullatt_block_indexes: [7, 15, 23, 31]
      hidden_act: silu
      hidden_size: 1024  
      in_channels: 3
      intermediate_size: 4096
      model_type: qwen2_5_vl
      num_heads: 16
      out_hidden_size: 1024
      patch_size: 14
      spatial_merge_size: 2
      temporal_patch_size: 2
      tokens_per_second: 4
      transformers_version: 4.49.0
      window_size: 112
      _attn_implementation: eager
      proj_size: 512
      torch_dtype: bfloat16
      seq_len: 341
      video_token_id: 151656

    loss_cfg:
      # rank: 0
      world_size: 1
      loss_dist_impl: gather
      
        
